"""empty message

Revision ID: f07ef76259fd
Revises: b86e5590504c
Create Date: 2022-01-26 15:05:01.696050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f07ef76259fd'
down_revision = 'b86e5590504c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('incorrect_answer1', sa.String(), nullable=False),
    sa.Column('incorrect_answer2', sa.String(), nullable=False),
    sa.Column('Incorrect_answer3', sa.String(), nullable=False),
    sa.Column('card_tableID', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_table')
    op.drop_table('card_set')
    # ### end Alembic commands ###
